### ISSUE TITLE
Enhancement Request - NOT AN ISSUE

### ISSUE THREAD

**Issue by j9mist** [yblake/deltaViz#10]
First of all, this is an AWESOME extension!!!

I am new to QS and this is absolutely a great and easy extension in terms of usage. 

I have two suggestions that you might want to consider:

FIRST:
I believe a great enhancements would be to define a target visualization when using a Drill Down dimension and reaching the last level. As designed, getting to the last drill node will only show one giant tile and instead of that, if you can expose a property to allow rendering a named visual, it would be extremely useful.

SECOND:
It would also be useful if you can sort tiles based on ascending/descending variance values. The extension calculates a variance but I am not sure how to sort by this value. This maybe a user error for all I know but if not, it might be useful to sort from highest to lowest variance to help direct the users attention better.

Just a thought.

**Comment by yblake** [comment]
Hi  @j9mist ,

Thanks for using deltaViz extension.

For your first suggest, I think your right but this may not be an easy thing to do. I've seen some "tab" extension able do dynamically change beetween master items visualization prts, I'll take a look... But definitely what would help for dynamic screen changes would be to have a display condition, like the good old one we were used to in QlikView...

For the second one, you can do it in the Sort properties panel. Change your dimension sort from Auto to Custom, then click on "Sort by expression" then you can enter any sort expression formula, i.e. like _fabs(Sum(SalesYtd2017) - sum(SalesYtd2016))_

Regards

**Comment by j9mist** [comment]
Hi @yblake,

Thank you for your prompt response. I had another question for you I was hoping you may be able to help with.

Is it possible to fix the size of the tiles so they are not dynamically changing when using a drill dimension. For example, I have a drill dimension which may have three levels of drill, the first has 10 elements, the second has 2 elements, and the third has 30 elements.

It would be very nice if we can set 1) number of tiles in a given row, 2) size of the tile (width/height), or 3) both. Marry this up with a horizontal and vertical scroll-bar would make this an interesting visual. 

This was one of the feedback I received in my application by a user who has a visual disability and was finding it hard to transition from one level to next. The user thought it would be easier on the eyes and would help maintain subject context if they fixated on a number and the size of the number didn't change from one layer to the next.

Regards.

**Comment by j9mist** [comment]
Hi @yblake,

Per my previous request of allowing users to define the size of the tiles, see attached the adjustment I've made to the extension. One last piece I can't seem to figure out is how to introduce scroll bars when I define a tile size to be static. Any ideas? I thought I would add a CSS element on row 663 by changing 

$element.append($('<div />;').attr('id', id).width(width).height(height));
to
$element.append($('<div />;').attr('id', id).width(width).height(height).css("overflow-y","auto"));

but no luck. 

I should mention I am not a web-developer so javascript changes and how DIVs function are not my forte.

Any help you can provide in creating a scrollable visual would be very appreciated.

Thanks

[graphics-deltaviz-delta.txt](https://github.com/yblake/deltaViz/files/1524106/graphics-deltaviz-delta.txt)

**Comment by yblake** [comment]
From other issue I can see that you found your way to add required features. Glad for you.
