### ISSUE TITLE
Authentication windows a lot of times

### ISSUE THREAD

**Issue by samaniego1971** [yblake/deltaViz#12]
We have a problem with this extension, every single time that we open a report that includes this extension it "pop-op" a window that is asking for credentials. Can you help us to solve this problem. please?
 
![CDD480A1](https://user-images.githubusercontent.com/48930102/54974126-8050b500-4f58-11e9-8eda-460fe9e717f0.PNG)

**Comment by yblake** [comment]
No se puede reproducir en casa. ¿ Puedes decime lo que dice la consola Javascript del desarrollador ?

**Comment by samaniego1971** [comment]
hello. thanks for your answer. I look for what I request and I found this error. I hope it helps

![error_401_extension](https://user-images.githubusercontent.com/48930102/55026338-6949ab80-4fc8-11e9-8d23-05e471256a74.PNG)

**Comment by yblake** [comment]
From what I can see in above screen, it could be related to background image "background.png" that is shown as a broken link...
Could you try to comment out lines 943 to 949 in graphics-deltaviz-delta.js; and refresh page ?

```
	/*tile.filter(function(d) { return d.item === null }).append('svg:image')
		.attr('x',cx-iw/2)
		.attr('y',cy-iw/2)
		.attr('width', iw)
		.attr('height', iw)
		.attr('xlink:href','/extensions/graphics-deltaviz-delta/background.png')
	;*/

```

_Note; You should keep dev tools console open on application sheet; and refresh it with "Empty cache and hard reload" to see changes, see :_ 
[What's the difference between “Normal Reload”, “Hard Reload”, and “Empty Cache and Hard Reload” in Chrome?](https://stackoverflow.com/questions/14969315/whats-the-difference-between-normal-reload-hard-reload-and-empty-cache-a)

**Comment by yblake** [comment]
Let's assume silence means ok.
