### ISSUE TITLE
Visualizations failed to render after adding dimension and measures

### ISSUE THREAD

**Issue by Shivshankarsharma** [yblake/deltaViz#2]
Kudos to the team.. Its worthy effort..

Can you please help me getting it executed.. 

I added d3.min.js file at the root. I have changed this in graphics-deltaviz-delta.js file - define(["jquery", "text!./graphics-deltaviz-delta.css", "./d3.min"
to
define(["jquery", "text!./graphics-deltaviz-delta.css", "./d3.min.js"

this made object to work and allowed to enter dimension and measures.

then i have added dimension and measures in QS but after this an error is appearing stating "visualizations failed to render".

Demo app is showing same message.. I have 64 bit machine and 1.0.2 version of QSense.

**Comment by Shivshankarsharma** [comment]
I got the solution .....thanks a lot....

**Comment by yblake** [comment]
Hi @shiv
What error do you have ? You can check error messages i.e. in Chrome Console using CTRL+SHIFT+J

**Comment by Shivshankarsharma** [comment]
Thanks blake for the Reply.. Sorry for being late, its working now....
