### ISSUE TITLE
Color change to be dynemic.

### ISSUE THREAD

**Issue by Shivshankarsharma** [yblake/deltaViz#3]
Dear Y Blake, 
I tried using your app in below business case and it contradicts. 

For lower  expenses,  I need color to be reversed (Green if expenses are less). But App is showing red color. 

example - Budgeted Value 1,00,000 Actual Value 75,000. 

This should show -25% (Which is correct now also) and color should be green )Now its red).

So kindly bring one option of reverse color.

Its great if you allow to chose color for -ve and +ve % value.

It would be fantastic if multicolor based on range is allowed

Example- Green for range -100 to -90, Yellow 90 to 100 and Red for 0 to 100

**Comment by yblake** [comment]
Hi,
This is not an issue, but I'll keep as new feature request. 
May be the new range slider property in Sense 1.1 will help for that.
We have to handle the fact that sometime you may have expenses AND ressources in same data, i.e. when you analyze an accountancy balance.
