### ISSUE TITLE
Seems to be broken in QlikSense 1.1

### ISSUE THREAD

**Issue by rvaheldendaten** [yblake/deltaViz#4]
HI!

As stated on branch.qlikview.com quite some people have problems to make this running in QlikSense1.1; The visualization still can be dragged to the sheet, but then fails with an error message!

![qlik sense desktop_2015-02-24_08-59-57](https://cloud.githubusercontent.com/assets/11175181/6348543/e299db1c-bc20-11e4-8ea8-c27309e8b78b.png)

**Comment by yblake** [comment]
This is a translation issue inside Sense 1.1 Desktop
. 
For unknown reason when using Sense 1.1 Desktop (Chromium) the navigator.languages array is now defined, but empty. 

I'll fix shortly the following instruction 
"var locale = navigator.languages ? navigator.languages[0] : <code>" 
to 
"var locale = (navigator.languages && navigator.languages.length > 0) ? navigator.languages[0] : <code>"

**Comment by yblake** [comment]
Fixed in v1.1
