### ISSUE TITLE
Change the colors

### ISSUE THREAD

**Issue by gersonjunior87** [yblake/deltaViz#6]
Hi,

Thank you for the amazing extension.
Can i change the colors?
I tried in "graphics-deltaviz-delta.js", but when i open the qlik sense, the colors never change.

Thank you.

**Comment by yblake** [comment]
Seems like a Chrome cache issue... I use this to clean Sense Desktop cache :
 
In Qlik Sense Desktop, Open your application, then activate Chrome Dev tools by pressing **CTRL+SHIFT+Right click**, then select "**Show Dev tools**" menu item.
 
In Chrom Dev Tools tab, click on Settings icon (up right the screen) and set first option on :
"**Disable cache (while DevTools is open)**". Then close Dev tools settings.
 
Go back to your application Tab, and refresh your application display using **CTRL+F5** (or press reload button for a while to get cache clear reload options).
 
Hope this help,
Regards

**Comment by gersonjunior87** [comment]
yblake,

Thank you so much! Working now.
One more help. I have 2 panels: In one i need that positive or negative values in red. In the other panel, the colors will follow the default pattern. Is it possible do that? I duplicated the extension through the dev-hub (and changed the colors in one), but even with 2 extensions the default is always the same.

Thanks,
Gerson

**Comment by gersonjunior87** [comment]
Can you help me?

**Comment by yblake** [comment]
Just set "Invert colors" on in order to get postive deviations in red and negative in green
