### ISSUE TITLE
Problem with using formula in dimension

### ISSUE THREAD

**Issue by bbainsslalom** [yblake/deltaViz#9]
DeltaViz is indicating that a dimension I defined via a formula is invalid, but the QlikSense editor is saying it's valid. DeltaViz doesn't present an error message, just crosshatches the dimension with red lines. This is my formula: =Date(Min({1<**PrevM1**={1}>} **SupplyChainDate**), 'MMM YYYY') & ' - ' & Date(Max({1<**CurMonth**={1}>} **SupplyChainDate**), 'MMM YYYY'). Bolded items are fields from my data model. This formula uses set expressions. Please advice.

**Comment by yblake** [comment]
Can't reproduce without your data... 
Do you have any error essage in Chrome development tools console ?
